In [10]:
from CustomerDAO import CustomerDAO

In [11]:
a=2

In [12]:
a

2

In [13]:
dao = CustomerDAO('customers_db.db')
#  list(dao.findAll())

In [14]:
# ! pip install numpy pandas

In [15]:
import numpy as np
x = np.arange(15,dtype=np.int64)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
x = x.reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
x.max(axis=1)

array([ 4,  9, 14])

In [19]:
x.max(axis=0)

array([10, 11, 12, 13, 14])

In [20]:
import pandas as pd
customers = dao.findAll()
df_customers = pd.DataFrame(customers)
df_customers

id first_name    last_name                     email  gender  \
0        1     Matias  Jacqueminet   mjacqueminet0@wikia.com    Male   
1        2     Bealle     Cornbill      bcornbill1@tmall.com    Male   
2        3     Israel    Edgington        iedgington2@ft.com    Male   
3        4      Bowie       Hafner          bhafner3@ftc.gov    Male   
4        5    Quinlan    Mulqueeny      qmulqueeny4@lulu.com    Male   
...    ...        ...          ...                       ...     ...   
2995  2996     Ricard       Culver         rculverrn@icq.com    Male   
2996  2997    Salaidh     Willoway   swillowayro@histats.com  Female   
2997  2998  Harrietta      Minards  hminardsrp@pinterest.com  Female   
2998  2999       Inga        Canet  icanetrq@fastcompany.com  Female   
2999  3000     Lucais  Pickersgill  lpickersgillrr@baidu.com    Male   

           ip_address  
0         188.0.156.6  
1         11.35.70.15  
2     134.210.113.151  
3      171.66.222.153  
4       85.180.97.200  
...               ...  
2995  154.247.237.253  
2996  196.159.162.209  
2997   223.74.223.203  
2998    87.149.28.130  
2999    182.87.23.110  

[3000 rows x 6 columns]

In [21]:
df_customers.head()

id first_name    last_name                    email gender       ip_address
0   1     Matias  Jacqueminet  mjacqueminet0@wikia.com   Male      188.0.156.6
1   2     Bealle     Cornbill     bcornbill1@tmall.com   Male      11.35.70.15
2   3     Israel    Edgington       iedgington2@ft.com   Male  134.210.113.151
3   4      Bowie       Hafner         bhafner3@ftc.gov   Male   171.66.222.153
4   5    Quinlan    Mulqueeny     qmulqueeny4@lulu.com   Male    85.180.97.200

In [22]:
df_customers.tail()

id first_name    last_name                     email  gender  \
2995  2996     Ricard       Culver         rculverrn@icq.com    Male   
2996  2997    Salaidh     Willoway   swillowayro@histats.com  Female   
2997  2998  Harrietta      Minards  hminardsrp@pinterest.com  Female   
2998  2999       Inga        Canet  icanetrq@fastcompany.com  Female   
2999  3000     Lucais  Pickersgill  lpickersgillrr@baidu.com    Male   

           ip_address  
2995  154.247.237.253  
2996  196.159.162.209  
2997   223.74.223.203  
2998    87.149.28.130  
2999    182.87.23.110

In [23]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   id          3000 non-null   int64 
 1   first_name  3000 non-null   object
 2   last_name   3000 non-null   object
 3   email       3000 non-null   object
 4   gender      3000 non-null   object
 5   ip_address  3000 non-null   object
dtypes: int64(1), object(5)
memory usage: 140.8+ KB


In [24]:
df_customers.describe()

id
count  3000.000000
mean   1500.500000
std     866.169729
min       1.000000
25%     750.750000
50%    1500.500000
75%    2250.250000
max    3000.000000

In [26]:
df_customers.columns
df_customers['last_name']

0       Jacqueminet
1          Cornbill
2         Edgington
3            Hafner
4         Mulqueeny
           ...     
2995         Culver
2996       Willoway
2997        Minards
2998          Canet
2999    Pickersgill
Name: last_name, Length: 3000, dtype: object

In [27]:
df_customers[(df_customers['gender']=="Male") & (df_customers['email'].str.contains('.com'))]

id first_name    last_name                     email gender  \
0        1     Matias  Jacqueminet   mjacqueminet0@wikia.com   Male   
1        2     Bealle     Cornbill      bcornbill1@tmall.com   Male   
2        3     Israel    Edgington        iedgington2@ft.com   Male   
4        5    Quinlan    Mulqueeny      qmulqueeny4@lulu.com   Male   
6        7     Pancho       Russon  prusson6@stumbleupon.com   Male   
...    ...        ...          ...                       ...    ...   
2987  2988       Niki       Mabbot         nmabbotrf@com.com   Male   
2988  2989    Silvain     Querrard  squerrardrg@netvibes.com   Male   
2994  2995      Jamil       Kildea      jkildearm@uol.com.br   Male   
2995  2996     Ricard       Culver         rculverrn@icq.com   Male   
2999  3000     Lucais  Pickersgill  lpickersgillrr@baidu.com   Male   

           ip_address  
0         188.0.156.6  
1         11.35.70.15  
2     134.210.113.151  
4       85.180.97.200  
6     127.112.247.147  
...               ...  
2987    57.142.126.42  
2988    35.255.191.83  
2994    158.76.58.234  
2995  154.247.237.253  
2999    182.87.23.110  

[846 rows x 6 columns]

In [28]:
df_customers['upper_last_name'] = df_customers['last_name'].str.upper()

In [29]:
df_customers

id first_name    last_name                     email  gender  \
0        1     Matias  Jacqueminet   mjacqueminet0@wikia.com    Male   
1        2     Bealle     Cornbill      bcornbill1@tmall.com    Male   
2        3     Israel    Edgington        iedgington2@ft.com    Male   
3        4      Bowie       Hafner          bhafner3@ftc.gov    Male   
4        5    Quinlan    Mulqueeny      qmulqueeny4@lulu.com    Male   
...    ...        ...          ...                       ...     ...   
2995  2996     Ricard       Culver         rculverrn@icq.com    Male   
2996  2997    Salaidh     Willoway   swillowayro@histats.com  Female   
2997  2998  Harrietta      Minards  hminardsrp@pinterest.com  Female   
2998  2999       Inga        Canet  icanetrq@fastcompany.com  Female   
2999  3000     Lucais  Pickersgill  lpickersgillrr@baidu.com    Male   

           ip_address upper_last_name  
0         188.0.156.6     JACQUEMINET  
1         11.35.70.15        CORNBILL  
2     134.210.113.151       EDGINGTON  
3      171.66.222.153          HAFNER  
4       85.180.97.200       MULQUEENY  
...               ...             ...  
2995  154.247.237.253          CULVER  
2996  196.159.162.209        WILLOWAY  
2997   223.74.223.203         MINARDS  
2998    87.149.28.130           CANET  
2999    182.87.23.110     PICKERSGILL  

[3000 rows x 7 columns]